- name: Configure portfolio VM
  hosts: portfolio
  become: true

  tasks:
    - name: Install Docker
      import_tasks: tasks/docker.yml

    - name: Install Nginx
      import_tasks: tasks/nginx.yml

    - name: Install Certbot
      import_tasks: tasks/certbot.yml
